#!/usr/bin/env python3
"""Generates src/core/SjisTable.inc: CP932 (Shift-JIS) double-byte -> Unicode table."""
import sys
leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD))
out = ["// Generated by tools/gen_sjis.py (CP932 double-byte characters). Do not edit.",
       "// Index: leadIndex * 189 + (trail - 0x40); 0 = unmapped.",
       "static const unsigned short kSjisTable[%d] = {" % (len(leads) * 189)]
row = []
count = 0
for lead in leads:
    for trail in range(0x40, 0xFD):
        u = 0
        if trail != 0x7F:
            try:
                s = bytes([lead, trail]).decode("cp932")
                if len(s) == 1 and ord(s) < 0x10000: u = ord(s); count += 1
            except UnicodeDecodeError:
                pass
        row.append("0x%X" % u if u else "0")
        if len(row) == 24:
            out.append("    " + ",".join(row) + ","); row = []
if row: out.append("    " + ",".join(row) + ",")
out.append("};")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("mapped", count)
