#!/usr/bin/env python3
"""Generates insdef/Yamaha MU2000.ins from the voice database inside TMIDI Player 3.8.6 (TMIDI.EXE).

TMIDI.EXE stores its instrument names as 20-byte records:
    byte 0      table id (0x08 = Yamaha XG normal voices, 0x09 = XG drum/SFX kits,
                          0x0A = XG bank names, 0x04 = Roland GS by map, ...)
    byte 1      XG: bank LSB            (Roland: tone map)
    byte 2      XG: bank MSB            (Roland: variation, i.e. bank MSB)
    byte 3      program (0-based)
    bytes 4-19  name, zero padded

The drum note names of the kits come from Yamaha XG.ins (tools/gen_ins.py); the kits only the
MU1000/MU2000 have are listed here, from the MU1000/MU2000 list book (tools/xg_drum_lists.py).

usage: gen_ins_tmidi.py path/to/TMIDI.EXE insdef/
"""
import os
import re
import sys
import collections
sys.dont_write_bytecode = True  # no __pycache__ in tools/
import xg_drum_lists


def records(exe):
    d = open(exe, "rb").read()
    # Locate the table: the longest run of well-formed records with a 20-byte stride.
    def ok(o):
        tid, b1, b2, prog = d[o], d[o + 1], d[o + 2], d[o + 3]
        if tid == 0xFF:
            return True
        raw = d[o + 4:o + 20]
        n = raw.split(b"\x00")[0]
        return tid < 0x40 and b1 < 128 and b2 < 128 and prog < 128 and 0 < len(n) and all(c == 0 for c in raw[len(n):])
    anchor = d.find(b"Nylon Guitar\x00")
    if anchor < 0:
        raise SystemExit("voice table not found")
    start = anchor - 4
    # Walk to the table start / end, tolerating a few malformed records.
    def walk(o, step):
        bad = 0
        last = o
        while 0 <= o < len(d) - 20 and bad < 50:
            if ok(o):
                bad = 0
                last = o
            else:
                bad += 1
            o += step
        return last
    first = walk(start, -20)
    last = walk(start, 20)
    out = []
    for o in range(first, last + 20, 20):
        if not ok(o) or d[o] == 0xFF:
            continue
        raw = d[o + 4:o + 20].split(b"\x00")[0]
        out.append((d[o], d[o + 1], d[o + 2], d[o + 3], raw.decode("cp932", "replace")))
    return out


def main():
    exe, outdir = sys.argv[1], sys.argv[2]
    recs = records(exe)
    bank_names = {r[2]: r[4].strip() for r in recs if r[0] == 0x0A and r[1] == 0}
    voices = collections.defaultdict(dict)   # (msb, lsb) -> {prog: name}
    kits = collections.defaultdict(dict)     # msb -> {prog: name}
    for tid, b1, b2, prog, name in recs:
        if tid == 0x08:
            if re.fullmatch(r"Voice\d{3}", name):
                continue  # placeholders (speech/user banks)
            voices[(b2, b1)][prog] = name.strip()
        elif tid == 0x09:
            if b2 not in (126, 127):
                continue  # misread records: XG drum kits are on MSB 127, SFX kits on MSB 126
            kits[b2][prog] = name.lstrip("#").strip()

    lines = ["; ----------------------------------------------------------------------",
             "; Cakewalk Instrument Definition File",
             "; Yamaha MU2000 / MU1000 / MU128 (XG) voices",
             "; Generated by tools/gen_ins_tmidi.py from the voice table in TMIDI Player 3.8.6",
             "; ----------------------------------------------------------------------", "", ".Patch Names", ""]
    for (msb, lsb) in sorted(voices):
        bank = bank_names.get(msb, "").strip()
        lines.append("[Yamaha MU2000 MSB %d LSB %d%s]" % (msb, lsb, (" " + bank) if bank else ""))
        for prog, name in sorted(voices[(msb, lsb)].items()):
            lines.append("%d=%s" % (prog, name))
        lines.append("")
    for msb in sorted(kits):
        lines.append("[Yamaha MU2000 %s]" % ("Drum Kits" if msb == 127 else "SFX Kits"))
        for prog, name in sorted(kits[msb].items()):
            lines.append("%d=%s" % (prog, name))
        lines.append("")
    # Note names of the kits only the MU1000/MU2000 have (the others are in Yamaha XG.ins).
    mu = xg_drum_lists.load()
    lines += [".Note Names", ""]
    keys = []
    for key, (kit, _) in sorted(xg_drum_lists.MU_KITS.items()):
        name = "Yamaha MU2000 " + kit
        lines.append("[%s]" % name)
        # Whole lists: a BasedOn list of another file (Yamaha XG.ins loads later) would not be found.
        notes = xg_drum_lists.kit_notes(mu, key)
        lines += ["%d=%s" % kv for kv in sorted(notes.items())] + [""]
        keys.append("Key[%d,%d]=%s" % (key[0] * 128, key[1], name))
    for key, (kit, _) in sorted(xg_drum_lists.XG_KITS.items(), key=lambda kv: kv[0][1]):
        if key != (127, 0):
            keys.append("Key[16256,%d]=Yamaha XG %s" % (key[1], kit))
    lines += [".Instrument Definitions", "", "[Yamaha MU2000]"]
    for (msb, lsb) in sorted(voices):
        bank = bank_names.get(msb, "").strip()
        lines.append("Patch[%d]=Yamaha MU2000 MSB %d LSB %d%s" % (msb * 128 + lsb, msb, lsb, (" " + bank) if bank else ""))
    lines.append("Patch[*]=Yamaha MU2000 MSB 0 LSB 0")
    lines += ["", "[Yamaha MU2000 Drums]"]
    for msb in sorted(kits):
        lines.append("Patch[%d]=Yamaha MU2000 %s" % (msb * 128, "Drum Kits" if msb == 127 else "SFX Kits"))
    # Drum note names: the kits of Yamaha XG.ins and the MU1000/MU2000 ones above.
    lines += ["Patch[*]=Yamaha MU2000 Drum Kits"] + keys + ["Key[*,*]=Yamaha XG Standard Kit", "Drum[*,*]=1", ""]
    path = os.path.join(outdir, "Yamaha MU2000.ins")
    with open(path, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines))
    print("banks", len(voices), "voices", sum(len(v) for v in voices.values()), "kits", sum(len(v) for v in kits.values()), "->", path)


if __name__ == "__main__":
    main()
