#!/usr/bin/env python3
"""Generates Cakewalk .ins instrument definitions for Yamaha XG, General MIDI and
General MIDI Level 2 that are not part of the Roland insdef set.

Inputs (text extracted from the public documents):
  QY100E2.txt   - Yamaha QY100 Data List (XG Normal/SFX voice list, XG drum voice list)
  gm2.wiki      - Wikipedia "General MIDI Level 2" article wikitext
and, for the note lists of the XG drum kits other than the Standard Kit and the SFX kits,
  reference/openmidiproject/MU1000_MU2000.ins (see tools/xg_drum_lists.py)
"""
import re, sys, os
sys.dont_write_bytecode = True  # no __pycache__ in tools/
import xg_drum_lists

def write_ins(path, title, sections):
    with open(path, "w", newline="\r\n") as f:
        f.write("; ----------------------------------------------------------------------\n")
        f.write("; Cakewalk Instrument Definition File\n; %s\n; Generated by tools/gen_ins.py for ImMidi\n" % title)
        f.write("; ----------------------------------------------------------------------\n\n")
        for kind in (".Patch Names", ".Note Names", ".Instrument Definitions"):
            f.write(kind + "\n\n")
            for name, lines in sections.get(kind, []):
                f.write("[%s]\n" % name)
                for l in lines: f.write(l + "\n")
                f.write("\n")

# ---------------------------------------------------------------- XG
def parse_xg_normal(txt):
    pages = re.split(r"=====PAGE (\d+)=====", txt)
    body = ""
    for i in range(1, len(pages), 2):
        if pages[i] in ("2", "3"): body += pages[i + 1] + "\n"
    head, _, sfx = body.partition("128 0 Gunshot 1")
    head += "\n128 0 Gunshot 1\n"
    banks = {}   # lsb -> {prog: name}
    prog = 0
    for line in head.split("\n"):
        line = line.strip()
        m = re.match(r"^(.*?)\s+(\d)$", line)
        if not m: continue
        rest = m.group(1)
        toks = rest.split()
        # drop category tokens before the first pure number
        while toks and not toks[0].isdigit(): toks.pop(0)
        if not toks: continue
        nums = []
        while toks and toks[0].isdigit() and len(nums) < 2: nums.append(int(toks.pop(0)))
        name = " ".join(toks).strip()
        if not name: continue
        if len(nums) == 2 and nums[0] == prog + 1:
            prog, lsb = nums
        elif len(nums) == 2:
            # a name that starts with a number token
            lsb = nums[0]; name = str(nums[1]) + " " + name
        else:
            lsb = nums[0]
        banks.setdefault(lsb, {})[prog] = name
    # SFX voices (MSB 64): "N name elem" per program
    sfxv = {}
    for line in sfx.split("MSB=064")[0].split("\n"):
        m = re.match(r"^\s*(\d+)\s+(\S.*?)\s+(\d)\s*$", line)
        if m: sfxv[int(m.group(1))] = m.group(2)
    return banks, sfxv

def parse_xg_drums(txt):
    pages = re.split(r"=====PAGE (\d+)=====", txt)
    notes = {}
    for i in range(1, len(pages), 2):
        if pages[i] != "4": continue
        for line in pages[i + 1].split("\n"):
            m = re.match(r"^(\d+) [A-G]#? ?-?\d\s+(?:\d\s+)?(?:O\s+)?(.*?)\s+1(?:\s|$)", line)
            if m:
                n = int(m.group(1)); name = m.group(2)
                for a, b in (("Fin ger", "Finger"), ("Se q", "Seq"), ("Ti ght", "Tight"), ("Dr y", "Dry"),
                             ("Li ght", "Light"), ("Snapp y", "Snappy"), ("C ymbal", "Cymbal"), ("Hi gh", "High"),
                             ("Bon go", "Bongo"), ("Con ga", "Conga"), ("A gogo", "Agogo"), ("Lon g", "Long"),
                             ("Trian gle", "Triangle"), ("Jin gle", "Jingle")):
                    name = name.replace(a, b)
                notes[n] = name.strip()
    notes[49] = "Crash Cymbal 1"; notes[51] = "Ride Cymbal 1"
    return notes

# The SFX kits' notes (QY100 and PLG100-XG drum voice lists). The text of those lists has lost its
# columns, so the kit of each sound is written out here: instrument noises, nature and animals are
# SFX Kit 1; telephone, doors, vehicles, people and weapons SFX Kit 2.
XG_SFX_KIT_1 = [(36, 'Cutting Noise'), (37, 'Cutting Noise 2'), (38, 'Distorted Cutting Noise'), (39, 'String Slap'), (40, 'Bass Slide'), (41, 'Pick Scrape'), (52, 'Flute Key Click'), (68, 'Shower'), (69, 'Thunder'), (70, 'Wind'), (71, 'Stream'), (72, 'Bubble'), (73, 'Feed'), (84, 'Dog'), (85, 'Horse'), (86, 'Bird Tweet 2'), (90, 'Ghost'), (91, 'Maou')]
XG_SFX_KIT_2 = [(36, 'Phone Call'), (37, 'Door Squeak'), (38, 'Door Slam'), (39, 'Scratch Cut'), (40, 'Scratch H 3'), (41, 'Wind Chime'), (42, 'Telephone 2'), (52, 'Car Engine Ignition'), (53, 'Car Tires Squeal'), (54, 'Car Passing'), (55, 'Car Crash'), (56, 'Siren'), (57, 'Train'), (58, 'Jet Plane'), (59, 'Starship'), (60, 'Burst'), (61, 'Roller Coaster'), (62, 'Submarine'), (68, 'Laugh'), (69, 'Scream'), (70, 'Punch'), (71, 'Heart Beat'), (72, 'Foot Steps'), (84, 'Machine Gun'), (85, 'Laser Gun'), (86, 'Explosion'), (87, 'Firework')]

XG_KITS = {1: "Standard Kit", 2: "Standard Kit 2", 3: "Dry Kit", 4: "Bright Kit", 9: "Room Kit",
           10: "Dark Room Kit", 17: "Rock Kit", 18: "Rock Kit 2", 25: "Electro Kit", 26: "Analog Kit",
           27: "Analog Kit 2", 28: "Dance Kit", 29: "Hip Hop Kit", 30: "Jungle Kit", 33: "Jazz Kit",
           34: "Jazz Kit 2", 41: "Brush Kit", 49: "Symphony Kit", 113: "R&B Kit", 114: "Rock Kit 3"}

def gen_xg(qy, out):
    txt = open(qy, encoding="utf-8").read()
    banks, sfxv = parse_xg_normal(txt)
    notes = parse_xg_drums(txt)
    patch = []
    for lsb in sorted(banks):
        patch.append(("Yamaha XG Bank %d" % lsb, ["%d=%s" % (p - 1, n) for p, n in sorted(banks[lsb].items())]))
    patch.append(("Yamaha XG SFX Voices", ["%d=%s" % (p - 1, n) for p, n in sorted(sfxv.items())]))
    patch.append(("Yamaha XG Drum Kits", ["%d=%s" % (p - 1, n) for p, n in sorted(XG_KITS.items())]))
    patch.append(("Yamaha XG SFX Kits", ["0=SFX Kit 1", "1=SFX Kit 2"]))
    note = [("Yamaha XG Standard Kit", ["%d=%s" % (n, s) for n, s in sorted(notes.items())]),
            ("Yamaha XG SFX Kit 1", ["%d=%s" % (n, s) for n, s in XG_SFX_KIT_1]),
            ("Yamaha XG SFX Kit 2", ["%d=%s" % (n, s) for n, s in XG_SFX_KIT_2])]
    # The other kits: the Standard Kit with their own sounds (MU1000/MU2000 list book).
    mu = xg_drum_lists.load()
    keys = []
    for key, (kit, _) in sorted(xg_drum_lists.XG_KITS.items(), key=lambda kv: kv[0][1]):
        if key == (127, 0):
            continue
        own = xg_drum_lists.own_notes(mu, key, notes)
        note.append(("Yamaha XG " + kit, ["BasedOn=Yamaha XG Standard Kit"] + ["%d=%s" % kv for kv in sorted(own.items())]))
        keys.append("Key[16256,%d]=Yamaha XG %s" % (key[1], kit))
    inst = [("Yamaha XG", ["Patch[%d]=Yamaha XG Bank %d" % (lsb, lsb) for lsb in sorted(banks)] +
             ["Patch[8192]=Yamaha XG SFX Voices", "Patch[*]=Yamaha XG Bank 0"]),
            ("Yamaha XG Drums", ["Patch[16256]=Yamaha XG Drum Kits", "Patch[16128]=Yamaha XG SFX Kits",
                                 "Patch[*]=Yamaha XG Drum Kits", "Key[16128,0]=Yamaha XG SFX Kit 1",
                                 "Key[16128,1]=Yamaha XG SFX Kit 2"] + keys + ["Key[*,*]=Yamaha XG Standard Kit", "Drum[*,*]=1"])]
    write_ins(out, "Yamaha XG (XG voice set as listed in the Yamaha QY100 data list; drum kits other than\n"
                   "; the Standard and SFX kits from the MU1000/MU2000 list book, after the instrument definition\n"
                   "; by kuzu / openmidiproject)",
              {".Patch Names": patch, ".Note Names": note, ".Instrument Definitions": inst})
    print("XG banks:", len(banks), "voices:", sum(len(v) for v in banks.values()), "sfx:", len(sfxv), "drum notes:", len(notes))

# ---------------------------------------------------------------- GM / GM2
def clean_wiki(s):
    s = re.sub(r"\[\[(?:[^|\]]*\|)?([^\]]*)\]\]", r"\1", s)
    s = re.sub(r"<ref.*?(/>|</ref>)", "", s)
    s = re.sub(r"'''?", "", s)
    return s.strip()

def parse_gm2(wiki):
    txt = open(wiki, encoding="utf-8").read()
    mel = txt.split("====Melodic sounds====")[1].split("==== Drum sounds ====")[0]
    rows = mel.split("|-")
    voices = {}   # (prog, bank) -> name
    prog = None
    for r in rows:
        cells = [c.strip() for c in r.strip().split("\n") if c.strip().startswith("|") and not c.strip().startswith("|}")]
        cells = [c[1:].strip() for c in cells]
        cells = [c.split("|")[-1].strip() if not c.startswith("[[") and "|" in c and "=" in c.split("|")[0] else c for c in cells]
        if not cells: continue
        if len(cells) == 3:
            if not cells[1].isdigit(): continue
            m = re.search(r"(\d+)\s*$", cells[0]); prog = int(m.group(1)); bank = int(cells[1]); name = clean_wiki(cells[2])
        elif len(cells) == 2 and prog is not None and cells[0].isdigit():
            bank = int(cells[0]); name = clean_wiki(cells[1])
        else:
            continue
        voices[(prog, bank)] = name
    kits = {1: "Standard Kit", 9: "Room Kit", 17: "Power Kit", 25: "Electronic Kit", 26: "TR-808 Kit",
            33: "Jazz Kit", 41: "Brush Kit", 49: "Orchestra Kit", 57: "Sound FX Kit"}
    return voices, kits

GM_DRUM_NOTES = {27: "High Q", 28: "Slap", 29: "Scratch Push", 30: "Scratch Pull", 31: "Sticks",
    32: "Square Click", 33: "Metronome Click", 34: "Metronome Bell", 35: "Acoustic Bass Drum", 36: "Bass Drum 1",
    37: "Side Stick", 38: "Acoustic Snare", 39: "Hand Clap", 40: "Electric Snare", 41: "Low Floor Tom",
    42: "Closed Hi-Hat", 43: "High Floor Tom", 44: "Pedal Hi-Hat", 45: "Low Tom", 46: "Open Hi-Hat",
    47: "Low-Mid Tom", 48: "Hi-Mid Tom", 49: "Crash Cymbal 1", 50: "High Tom", 51: "Ride Cymbal 1",
    52: "Chinese Cymbal", 53: "Ride Bell", 54: "Tambourine", 55: "Splash Cymbal", 56: "Cowbell",
    57: "Crash Cymbal 2", 58: "Vibraslap", 59: "Ride Cymbal 2", 60: "Hi Bongo", 61: "Low Bongo",
    62: "Mute Hi Conga", 63: "Open Hi Conga", 64: "Low Conga", 65: "High Timbale", 66: "Low Timbale",
    67: "High Agogo", 68: "Low Agogo", 69: "Cabasa", 70: "Maracas", 71: "Short Whistle", 72: "Long Whistle",
    73: "Short Guiro", 74: "Long Guiro", 75: "Claves", 76: "Hi Wood Block", 77: "Low Wood Block",
    78: "Mute Cuica", 79: "Open Cuica", 80: "Mute Triangle", 81: "Open Triangle", 82: "Shaker",
    83: "Jingle Bell", 84: "Belltree", 85: "Castanets", 86: "Mute Surdo", 87: "Open Surdo"}

def gen_gm(wiki, out_gm, out_gm2):
    voices, kits = parse_gm2(wiki)
    gm1 = {p: n for (p, b), n in voices.items() if b == 0}
    assert len(gm1) == 128, len(gm1)
    notes = [("General MIDI Drums", ["%d=%s" % kv for kv in sorted(GM_DRUM_NOTES.items())])]
    write_ins(out_gm, "General MIDI Level 1",
        {".Patch Names": [("General MIDI", ["%d=%s" % (p - 1, n) for p, n in sorted(gm1.items())]),
                          ("General MIDI Drum Kits", ["0=Standard Kit"])],
         ".Note Names": notes,
         ".Instrument Definitions": [("General MIDI", ["Patch[*]=General MIDI"]),
                                     ("General MIDI Drums", ["Patch[*]=General MIDI Drum Kits",
                                      "Key[*,*]=General MIDI Drums", "Drum[*,*]=1"])]})
    banks = sorted({b for (p, b) in voices})
    patch = [("GM2 Bank %d" % b, ["%d=%s" % (p - 1, n) for (p, bb), n in sorted(voices.items()) if bb == b]) for b in banks]
    patch.append(("GM2 Drum Kits", ["%d=%s" % (p - 1, n) for p, n in sorted(kits.items())]))
    write_ins(out_gm2, "General MIDI Level 2",
        {".Patch Names": patch, ".Note Names": [("GM2 Drums", ["%d=%s" % kv for kv in sorted(GM_DRUM_NOTES.items())])],
         ".Instrument Definitions": [("General MIDI Level 2", ["Patch[%d]=GM2 Bank %d" % (121 * 128 + b, b) for b in banks] +
                                      ["Patch[*]=GM2 Bank 0"]),
                                     ("General MIDI Level 2 Drums", ["Patch[15360]=GM2 Drum Kits", "Patch[*]=GM2 Drum Kits",
                                      "Key[*,*]=GM2 Drums", "Drum[*,*]=1"])]})
    print("GM2 voices:", len(voices), "banks:", banks)

if __name__ == "__main__":
    src, dst = sys.argv[1], sys.argv[2]
    gen_xg(os.path.join(src, "QY100E2.txt"), os.path.join(dst, "Yamaha XG.ins"))
    gen_gm(os.path.join(src, "gm2.wiki"), os.path.join(dst, "General MIDI.ins"), os.path.join(dst, "General MIDI Level 2.ins"))
